### ISSUE TITLE
Displayed date is off by one day

### ISSUE THREAD

**Issue by rhaas79** [nggepe/calendar-gc#4]
Hello. First and foremost thank you so much for this calendar! It is awesome!
I've only found one issue with it and perhaps it is in the way I am using it, or the options I am passing.
It appears that all of the events I am creating are being displayed one day early. Please see attached screenshot for more details.
Am I doing something wrong?
Thank you!
![Capture](https://user-images.githubusercontent.com/99414021/185680460-7794831a-452a-4dfa-8c38-4a6668233e38.PNG)

**Comment by nggepe** [comment]
Hello, sorry for the late response. I don't get any notification from this issue. May I'll check this bug tomorrow.

**Comment by nggepe** [comment]
Hi, I've check this issue, but I cannot find that bug. can you share your complete code?

**Comment by XFBC** [comment]
Hello good morning, the dateJS function has this bug of returning a day earlier, what I did was use it in ISO 8601 format, for example:  date: new Date('2023-01-25T00:00:00').  and I wanted to thank you for the code, very usual
![image](https://user-images.githubusercontent.com/92175971/214321897-62e9fd13-4a80-4d8d-a6d5-22d555e148db.png)

![image](https://user-images.githubusercontent.com/92175971/214321962-a65b2df7-009c-4b45-a28e-66d20bc31fee.png)

**Comment by nggepe** [comment]
> Hello good morning, the dateJS function has this bug of returning a day earlier, what I did was use it in ISO 8601 format, for example: date: new Date('2023-01-25T00:00:00'). and I wanted to thank you for the code, very usual ![image](https://user-images.githubusercontent.com/92175971/214321897-62e9fd13-4a80-4d8d-a6d5-22d555e148db.png)
> 
> ![image](https://user-images.githubusercontent.com/92175971/214321962-a65b2df7-009c-4b45-a28e-66d20bc31fee.png)

Hi @XFBC , thank you for using this library, and give me some issue.
I saw that you set your event date at `2023-01-25` and `2023-02-27` in you code, where is the `earlier` case? your screenshot show the event at `2023-01-25`. Is that on the next month?

**Comment by XFBC** [comment]
Yes, the next event is showing next month. What I wanted to talk to you about is the dateJS error, which can be solved using the UTC format.

**Comment by nggepe** [comment]
Thanks @XFBC , sorry for miss reading 😄
