### ISSUE TITLE
No Associated License

### ISSUE THREAD

**Issue by kchason** [nggepe/calendar-gc#5]
Great work on this easy to use and simple calendar!

Currently this repository has no license associated with it, though there is reference to customization of this library.

Is this repository intended for open-source use, and if so, can a license be applied? 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by nggepe** [comment]
Hi, thank you for mentioning this issue.
Actually, this is an MIT license.
Sorry I'm forget to add the license to this repository. Maybe I'll add it when I in front of my laptop.

**Comment by kchason** [comment]
Awesome, thanks! Looks like this issue can be resolved.

I'm going to be using it for a project and made a few changes that I'll put in a pull request for in case you'd like to adopt them into this repository as well.

**Comment by nggepe** [comment]
Thanks a lot for creating a pull request, I'll check it.
